// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('google search', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('google search', async function() {
    // Test name: google search
    // Step # | name | target | value | comment
    // 1 | open | https://www.google.com/ |  | 
    await driver.get("https://www.google.com/")
    // 2 | selectFrame | index=0 |  | 
    await driver.switchTo().frame(0)
    // 3 | click | css=#introAgreeButton .RveJvd |  | 
    await driver.findElement(By.css("#introAgreeButton .RveJvd")).click()
    // 4 | selectFrame | relative=parent |  | 
    await driver.switchTo().defaultContent()
    // 5 | type | name=q | devops | 
    await driver.findElement(By.name("q")).sendKeys("devops")
    // 6 | sendKeys | name=q | ${KEY_ENTER} | 
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    // 7 | runScript | window.scrollTo(0,114) |  | 
    await driver.executeScript("window.scrollTo(0,114)")
    // 8 | click | css=.g:nth-child(8) .LC20lb > span |  | 
    await driver.findElement(By.css(".g:nth-child(8) .LC20lb > span")).click()
  })
})
