// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WandaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void wanda() {
    // Test name: wanda
    // Step # | name | target | value | comment
    // 1 | open | https://www.rottentomatoes.com/ |  | 
    driver.get("https://www.rottentomatoes.com/");
    // 2 | type | css=.search-text | Wandavision | 
    driver.findElement(By.cssSelector(".search-text")).sendKeys("Wandavision");
    // 3 | sendKeys | css=.search-text | ${KEY_ENTER} | 
    driver.findElement(By.cssSelector(".search-text")).sendKeys(Keys.ENTER);
    // 4 | runScript | window.scrollTo(0,171) |  | 
    js.executeScript("window.scrollTo(0,171)");
    // 5 | click | css=search-result-container |  | 
    driver.findElement(By.cssSelector("search-result-container")).click();
    // 6 | click | linkText=Episode 05 |  | 
    driver.findElement(By.linkText("Episode 05")).click();
    // 7 | mouseOver | linkText=Episode 05 |  | 
    {
      WebElement element = driver.findElement(By.linkText("Episode 05"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | runScript | window.scrollTo(0,171) |  | 
    js.executeScript("window.scrollTo(0,171)");
    // 9 | click | css=.cast-item:nth-child(1) .actorThumb |  | 
    driver.findElement(By.cssSelector(".cast-item:nth-child(1) .actorThumb")).click();
  }
}
